### ISSUE TITLE
Invalid JSON body response

### ISSUE THREAD

**Issue by EndermanHackerVN** [LilyAsFlora/reddit-fetch#41]
**Explain the problem**
- A detailed, clear summary of what the issue is.

everytime I run the module, my program crashes with this error:
`
return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://reddit.com/r/subredditname.json?sort=hot&t=week reason: Unexpected token B in JSON at position 0
`

**To Reproduce**
- List of detailed steps to reproduce the behavior:
Install reddit-fetch and do this code:
`
redditFetch({
            subreddit: `MikuNakano`,
            sort: 'hot',
            allowNSFW: true,
            allowModPost: true,
            allowCrossPost: true,
            allowVideo: false        
        }).then(post => {     
                  console.log(post)
        })
`

**Expected behavior**
It shouldn't crash and return the post in console.

**Screenshots**
![image](https://user-images.githubusercontent.com/67498765/143973797-a62f0a5e-2e11-4abf-89de-3073e5604658.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Node version: 16.13.0
 - Package version: 1.5.1

**Additional context**
N / A

**Comment by LilyAsFlora** [comment]
Hi Ender, I reproduced your code with the same node & package versions, and the program worked as expected. The error is being thrown by `node-fetch`, not `reddit-fetch`. What's probably happening, is that the server is returning HTML or plain text data, instead of the expected JSON. This might be happening for a few reasons:

- Your proxy is misconfigured 

- The URL doesn't exist — in which case the server returned a 404 page

**Comment by EndermanHackerVN** [comment]
@LilyAsFlora sure, thanks for the explaination
